application: course-mate
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static/scripts
  static_dir: static/scripts

- url: /static/css
  static_dir: static/css

- url: /static/images
  static_dir: static/images

- url: /static/data
  static_dir: static/data

- url: /static
  static_dir: static
  application_readable: true

- url: /.*
  script: course_mate.course_mate.app

libraries:
- name: jinja2
  version: latest

- name: markupsafe
  version: latest
