application: course-mate
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static/javascript
  static_dir: static/javascript

- url: /static/stylesheets
  static_dir: static/stylesheets

- url: /static/images
  static_dir: static/images

- url: /static
  static_dir: static
  application_readable: true

- url: /index
  script: course_mate.course_mate.app

libraries:
- name: jinja2
  version: latest

- name: markupsafe
  version: latest
